<a href="https://colab.research.google.com/github/franciscoerramuspe/tensorflow_guide/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We are going to cover:
* intro tensors
* getting info from tensors
* manipulatinmg tensors
* tensors and numpy
* using tf.fucntion()
* using gpus with tf



**Intro to tensors**

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.15.0


Create tensors with tf.constants()

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

Check the number of dimensions of a tensor

In [ ]:
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10, 10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[10, 7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Create another matrix
matrix2= tf.constant([[10., 7.],
                      [3., 2.],
                      [8., 9.]], dtype=tf.float16) #specify the data type parameter
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
matrix2.ndim

2

In [ ]:
# create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                       [10, 11, 12]],
                       [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

what we created so far:
* scalar: a single number
* vector: a number with direction (e.g wind/speed)
* matrix: a 2d array of nums
* tensor: an n-dimensional array of nums


### Creating tensors with `tf.Variable`

In [ ]:
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])
unchangable_tensor, changable_tensor


(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#changing obne of the elements in changable tensor
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# trying to change unchangable tensor
unchangable_tensor[0].assign(7)
unchangable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

##Creating Random Tensors
**Random Tensor:** Tensors of arbitrary size which contains random numbers


*   This is useful because it initializes tensors with random weights (only at the beginning)
*   Then you show the program some examples (e.g, showing photos of food and indicating which photos are ramen, assuming we are creating a model that identifies which plates are ramen(labeled ouptus))
* Updates representation ouputs



In [ ]:
# Create two random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

This is useful because we (usually) want to keep the order of our inputs as random as possible. For example:


*   If I have 20K photos of ramen and 10K photos of spaghetti, and all the photos of ramen come first before the photos of spaghetti then this order could affect how are NN learns
*   This may start to adjust its random weights to the images of ramen
* Therefore, it may be a good idea to mix up the imgs in our folders,so the NN could adjust its random patterns, and learn from both images at the same time



In [ ]:
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [2, 5]])
not_shuffled.ndim

2

In [ ]:
not_shuffled = tf.random.shuffle(not_shuffled)

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

Creating tensors from NumPy arrays

In [ ]:
# create a tensor of just ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create a tensor of all zeroes
tf.zeros(shape =(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### turn numpy arrays into tensors

the main difference between numpy arrays and tensors is that tensors can be run on a gpu (much faster for numerical computing)

In [ ]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4)) # the multiplication of these numbers must equal total items (in our case, 24)
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting info from tensors
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# get various attributes of our tensor
print("datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("shape of tensor:", rank_4_tensor.shape)
print("elements along 0 axis", rank_4_tensor.shape[0])
print("elements along last axis", rank_4_tensor.shape[-1])
print("total number of elements in tensor", tf.size(rank_4_tensor))
print("total number of elements in tensor", tf.size(rank_4_tensor).numpy())

datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
shape of tensor: (2, 3, 4, 5)
elements along 0 axis 2
elements along last axis 5
total number of elements in tensor tf.Tensor(120, shape=(), dtype=int32)
total number of elements in tensor 120


### Indexing and expanding tensors
Tensors can be indexed like python lists

In [ ]:
#get the first two elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# create a rank. w tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add an extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

###Manipulating tensors

**Basic operations**

In [ ]:
# add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# original tensor is unchanged

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#multiplication
tensor * 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1000,  700],
       [ 300,  400]], dtype=int32)>

In [ ]:
#subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# We can use the tenrosrflow built-in funcs
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

In [ ]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#with python operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#trying to multiply two incompatible matrices
tensor1 = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float32)
tensor2 = tf.constant([[7, 8], [9, 10], [11, 12]], dtype=tf.float32)

tensor1 @ tensor2

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [ ]:
# fixing the matrices to multiply them
tensor1 @ tf.reshape(tensor2, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 27.,  30.,  33.],
       [ 61.,  68.,  75.],
       [ 95., 106., 117.]], dtype=float32)>

In [ ]:
#changing tensor1 instead of tensor2
tf.reshape(tensor1, shape=(2,3)) @ tensor2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 58.,  64.],
       [139., 154.]], dtype=float32)>

In [ ]:
#matrix multiplication with transpose

In [ ]:
tf.matmul(tf.transpose(tensor1), tensor2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 89.,  98.],
       [116., 128.]], dtype=float32)>

**The dot Product**
Matrix multiplication is also referred as the dot product

it could be done using:
* `tf.matmul()`
* `tf.tensordot()`



In [ ]:
tensor1, tensor2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]], dtype=float32)>)

In [ ]:
# perform the dot product on tensor1 and tensor2 (requires tensor1 or tensor2 to be transposed)
result = tf.tensordot(tf.transpose(tensor1), tensor2, axes=1)
result

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 89.,  98.],
       [116., 128.]], dtype=float32)>

In [ ]:
# Perform matrix multiplication between tensors (transposed)
tf.matmul(tensor1, tf.transpose(tensor2))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 23.,  29.,  35.],
       [ 53.,  67.,  81.],
       [ 83., 105., 127.]], dtype=float32)>

In [ ]:
# Perform matrix multiplication between tensor 1 and 2 (reshaped)
tf.matmul(tensor1, tf.reshape(tensor2, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 27.,  30.,  33.],
       [ 61.,  68.,  75.],
       [ 95., 106., 117.]], dtype=float32)>

In [ ]:
#Check values of tensor2, and reshape tensor2 and transposed tensor2
print("normal tensor2:")
print(tensor2, "\n")

print("tensor2 reshaped to (2,3):")
print(tf.reshape(tensor2, (2,3)), "\n")

print("tensor2 transposed:")
print(tf.transpose(tensor2))

normal tensor2:
tf.Tensor(
[[ 7.  8.]
 [ 9. 10.]
 [11. 12.]], shape=(3, 2), dtype=float32) 

tensor2 reshaped to (2,3):
tf.Tensor(
[[ 7.  8.  9.]
 [10. 11. 12.]], shape=(2, 3), dtype=float32) 

tensor2 transposed:
tf.Tensor(
[[ 7.  9. 11.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32)


## Change tensor datatype

In [ ]:
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype= tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [ ]:
E_float16= tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

## Aggregating tensors
performing operations that combine the elements of a tensor to produce a summarized result. This can be thought of as a way to reduce the dimensions of a tensor by applying a specific operation across its elements.
There are several common types of aggregation operations, including:
* Sum
* Mean
* Max
* Min

In [ ]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100, size =50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([79, 37, 83, 95, 96,  0,  8, 36, 95, 71, 27, 18, 82, 44, 39, 99, 92,
       26, 47, 23, 53, 31,  5,  5, 40, 38, 90, 54, 45, 71, 14, 55, 51, 99,
       88, 52, 36, 49, 83, 75,  8, 85, 33, 95, 95, 50, 60, 27, 33, 28])>

In [72]:
# find the min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [73]:
#find the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [74]:
#find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [75]:
#Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2645>

In [77]:
# find the variance
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=871>

In [79]:
# find std
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.501356>

## Find the positinal max and min of a tensor

In [80]:
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.1091938 , 0.46501458, 0.14071321, 0.96620905, 0.48489082,
       0.96121407, 0.18994522, 0.3284961 , 0.15350628, 0.75262725,
       0.36056483, 0.66145384, 0.7269813 , 0.2675898 , 0.50272405,
       0.6758971 , 0.92122066, 0.31997836, 0.5174086 , 0.32131922,
       0.11480713, 0.33920038, 0.91334856, 0.15795743, 0.9711671 ,
       0.73194516, 0.5376493 , 0.58287084, 0.05190277, 0.7509321 ,
       0.84779143, 0.39906406, 0.8368577 , 0.43036628, 0.4325806 ,
       0.34700453, 0.9620906 , 0.29610646, 0.18409014, 0.00372052,
       0.7700038 , 0.9913074 , 0.844852  , 0.40584517, 0.08080971,
       0.5481703 , 0.05319488, 0.25959945, 0.9460397 , 0.89952826],
      dtype=float32)>

In [81]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=41>

In [82]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9913074>

In [83]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9913074>

In [84]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [85]:
# find the positional min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=39>

In [86]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.003720522>

### Squeezing a tensor (Removing all single dimensions)

In [89]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [90]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [91]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape # this remove all the extra ()

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

## One-hot encoding tensors
 powerful technique used to convert categorical data into a numerical format that machine learning models can work with more effectively. When we apply one-hot encoding to tensors, we're transforming categorical values into a format where each category is represented by a tensor (or vector) filled with zeros except for a single '1' indicating the presence of that category.